### ISSUE TITLE
Feature Requests & Questions links to tanstack router discussions

### ISSUE THREAD

**Issue by Shaglock** [TanStack/create-tsrouter-app#63]
### Which project does this relate to?

Create Tanstack App

### Describe the bug

It looks like github config issue template contact link leads to https://github.com/tanstack/router/discussions instead of https://github.com/TanStack/create-tsrouter-app/discussions, is that intended or not?

```yml
contact_links:
  - name: 🤔 Feature Requests & Questions
    url: https://github.com/tanstack/router/discussions
```

### Your Example Website or App

github.com

### Steps to Reproduce the Bug or Issue

1. when you try to create a new issue in this repository you will get a list of options
2. 🤔 Feature Requests & Questions links to tanstack router repo discussions

### Expected behavior

I expected it to lead https://github.com/TanStack/create-tsrouter-app/discussions, but maybe it's intended to link to router repo? 

### Platform

- OS:  macOS
- Browser: Safari,
